CREATE TABLE JAVA_CATEGORIA (
ID NUMBER GENERATED ALWAYS AS IDENTITY,
 CATEGORIA VARCHAR2(100) NOT NULL,

 CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID),
 CONSTRAINT UK_CATEGORIA UNIQUE (CATEGORIA)
);

CREATE TABLE JAVA_DESPESA (
   	ID NUMBER GENERATED ALWAYS AS IDENTITY,
 	DESCRICAO VARCHAR2(255),
	VALOR NUMBER(10,2) NOT NULL,
    	DATA DATE NOT NULL,
   	ID_CATEGORIA NUMBER NOT NULL,   

    CONSTRAINT PK_DESPESA PRIMARY KEY (ID),

   CONSTRAINT FK_DESPESA_CATEGORIA
       FOREIGN KEY (ID_CATEGORIA)
      REFERENCES JAVA_CATEGORIA(ID)
      ON DELETE CASCADE);

SELECT * FROM JAVA_CATEGORIA;
SELECT * FROM JAVA_DESPESA;

INSERT INTO JAVA_CATEGORIA (categoria) VALUES ('Vestuário');

INSERT INTO JAVA_DESPESA (DESCRICAO,VALOR,DATA,ID_CATEGORIA) VALUES ('camiseta',90,sysdate,2);

INSERT INTO JAVA_DESPESA (DESCRICAO,VALOR,DATA,ID_CATEGORIA) VALUES ('Fini',6,TO_DATE('02/08/2026'),1);