CREATE TABLE PEDIDO (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    DATA_PEDIDO DATE,
    CLIENTE VARCHAR2(100),
    VALOR_TOTAL NUMBER(10,2),

    CONSTRAINT PK_PEDIDO PRIMARY KEY (ID)
);

SELECT * FROM PEDIDO;
